apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-boot-k8s
  labels:
    app : {{ .Release.Name }}-spring-boot-k8s
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : {{ .Release.Name }}-spring-boot-k8s
          image: {{ .Values.container.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion : autoscaling/v2beta1
kind : HorizontalPodAutoscaler
metadata :
  name : {{ .Release.Name }}-spring-boot-k8s
spec :
  scaleTargetRef :
    apiVersion: apps/v2beta1v1
    kind : Deployment
    name : {{ .Release.Name }}-spring-boot-k8s-autoscaling
  minReplicas : 2
  maxReplicas : 5
  metrics :
    - type : Resource
      resource :
        name : cpu
        targetAverageUtilization : 80
    - type : Resource
      resource:
        name : memory
        targetAverageUtilization : 90